// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Form struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Schema      []byte      `json:"schema"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Submission struct {
	ID         pgtype.UUID `json:"id"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
	SchemaID   pgtype.UUID `json:"schema_id"`
	Data       []byte      `json:"data"`
	Metadata   []byte      `json:"metadata"`
	Status     string      `json:"status"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type Workflow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	SchemaID    pgtype.UUID `json:"schema_id"`
	Trigger     []byte      `json:"trigger"`
	Actions     []byte      `json:"actions"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
