// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateForm(ctx context.Context, arg *CreateFormParams) (*Form, error)
	CreateSubmission(ctx context.Context, arg *CreateSubmissionParams) (*Submission, error)
	CreateWorkflow(ctx context.Context, arg *CreateWorkflowParams) (*Workflow, error)
	DeleteForm(ctx context.Context, id pgtype.UUID) error
	DeleteSubmission(ctx context.Context, id pgtype.UUID) error
	DeleteWorkflow(ctx context.Context, id pgtype.UUID) error
	GetForm(ctx context.Context, id pgtype.UUID) (*Form, error)
	GetSubmission(ctx context.Context, id pgtype.UUID) (*Submission, error)
	GetWorkflow(ctx context.Context, id pgtype.UUID) (*Workflow, error)
	GetWorkflowSubmissionSummary(ctx context.Context, workflowID pgtype.UUID) (*GetWorkflowSubmissionSummaryRow, error)
	ListForms(ctx context.Context, ownerID pgtype.UUID) ([]*Form, error)
	ListSubmissions(ctx context.Context, workflowID pgtype.UUID) ([]*Submission, error)
	ListSubmissionsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]*Submission, error)
	ListWorkflows(ctx context.Context, ownerID pgtype.UUID) ([]*Workflow, error)
	UpdateForm(ctx context.Context, arg *UpdateFormParams) (*Form, error)
	UpdateSubmissionStatus(ctx context.Context, arg *UpdateSubmissionStatusParams) (*Submission, error)
	UpdateWorkflow(ctx context.Context, arg *UpdateWorkflowParams) (*Workflow, error)
	UpdateWorkflowStatus(ctx context.Context, arg *UpdateWorkflowStatusParams) (*Workflow, error)
}

var _ Querier = (*Queries)(nil)
